global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]
      - targets: ["192.168.1.4:9100"]
      - targets: ["192.168.1.30:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: "hayasuke_docker"
    static_configs:
      - targets: ["192.168.1.30:9323"]
